version: '2'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - GEOARTICLE_GEOCODE_URL=
      - GEOARTICLE_GEOCODE_APIKEY=
    restart: unless-stopped
    logging:
     options:
      max-size: "10M"
      max-file: "10"
  client:
    build: ./client
    ports:
      - "8003:80"
    environment:
      - GEOARTICLE_URL=
    restart: unless-stopped
    logging:
     options:
      max-size: "10M"
      max-file: "10"

