FROM python:3.7

RUN pip install --upgrade pip && pip install newspaper3k geotext flask flask-cors numpy requests haversine

RUN mkdir -p /src/logs

ENV FLASK_APP=/src/app.py

COPY ./src /src

EXPOSE 5000

ENTRYPOINT ["flask", "run", "--host=0.0.0.0"]
